// Generated by https://quicktype.io

import 'package:json_annotation/json_annotation.dart';
import 'package:valua_staff/models/subject.dart';
part 'semester.g.dart';

@JsonSerializable()
class Semester {
  String semesterId;
  String semesterName;
  List<Subject> subjects;
  String beginDate;
  String endDate;
  bool isActive;
  DateTime createdDate;
  DateTime lastModifiedDate;

  Semester({
    required this.semesterId,
    required this.semesterName,
    required this.subjects,
    required this.beginDate,
    required this.endDate,
    required this.isActive,
    required this.createdDate,
    required this.lastModifiedDate,
  });

  factory Semester.fromJson(Map<String, dynamic> json) =>
      _$SemesterFromJson(json);

  Map<String, dynamic> toJson() => _$SemesterToJson(this);
}
